services:
  blog-admin:
    ports: !reset []
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.blog-admin.rule=Host(`admin.mohits.dev`)
      - traefik.http.services.blog-admin.loadbalancer.server.port=80
      # Enable these when TLS is terminated by this Traefik instance.
      # - traefik.http.routers.blog-admin.entrypoints=websecure
      # - traefik.http.routers.blog-admin.tls=true
      # - traefik.http.routers.blog-admin.tls.certresolver=letsencrypt
    networks:
      - default
      - traefik

networks:
  traefik:
    external: true
